collector:
  address: 10.87.64.31:50055
devices:
- address: 10.84.192.15:50052
  namespace: "qfx1"
  user: mhenkel
  password: kadalh12
  cid: cid
  tls:
    cert_file: /home/mhenkel/collector-rs/jtimon-rs/tls/qfx2.crt
    key_file: /home/mhenkel/collector-rs/jtimon-rs/tls/qfx2.key
    ca_file: /home/mhenkel/collector-rs/jtimon-rs/tls/ca.crt
    server_name: ctolab-b2-qfx2.englab.juniper.net
  paths:
  - path: /junos/system/linecard/firewall/
    freq: 2000
  #- path: /junos/system/linecard/qmon-sw/
  #  freq: 2000
- address: 10.84.192.16:50052
  namespace: "qfx2"
  user: mhenkel
  password: kadalh12
  cid: cid
  tls:
    cert_file: /home/mhenkel/collector-rs/jtimon-rs/tls/qfx3.crt
    key_file: /home/mhenkel/collector-rs/jtimon-rs/tls/qfx3.key
    ca_file: /home/mhenkel/collector-rs/jtimon-rs/tls/ca.crt
    server_name: ctolab-b2-qfx3.englab.juniper.net
  paths:
  - path: /junos/system/linecard/firewall/
    freq: 2000
    label_regexps:
      byte_counter: "state/counter\\[name='([^']*)'\\]/byte"
    rate_keys:
      byte_rate: "state/counter\\[name='([^']*)'\\]/byte"
  #- path: /junos/system/linecard/qmon-sw/
  #  freq: 2000
